# Hexo Configuration
## Docs: http://zespia.tw/hexo/docs/configure.html
## Source: https://github.com/tommy351/hexo/

# Site
title: "Sergio Lepore - Coder, Blogger, Speaker, Open Source Fan"
subtitle:
description: >
    Changing the world, one line of code at a time.
    <br>
    Geek. Open Source enthusiast.
    <br>
    I'm an Ubuntu user and I'm damn proud of it.
    <br>
    Cats and JavaScript are my weakness.
author: Sergio Lepore
email: sergio.d.lepore@gmail.com
language: es

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://sergiolepore.github.io
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archivos
category_dir: categorias
code_dir: downloads/code

# Writing
new_post_name: :year-:month-:day-:title.md
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
highlight:
  enable: true
  line_number: true
  tab_replace: "  "

# Category & Tag
default_category: Varios
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:
# render_drafts: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname: sergiolepore

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes
theme: hexo-theme-greyshade
plugins:
  # - hexo-tag-gdriveimage
  - hexo-tag-emojis
  - hexo-broken-link-checker
  - hexo-generator-feed
exclude_generator:

# Deployment
## Docs: http://zespia.tw/hexo/docs/deploy.html
deploy:
  type: github
  repository: git@github.com:sergiolepore/sergiolepore.github.io.git

# hexo-tag-emojis plugin
emojis:
  # image_dir: images/emojis
  cdn: http://cdn.staticfile.org/emojify.js/0.9.0/emojis

# hexo-broken-link-checker
link_checker:
  enabled: true
  storage_dir: temp/link_checker

# hexo-generator-feed
feed:
  type: rss2
  path: rss.xml
  limit: 50